### ISSUE TITLE
Week 14 Feedback 2 of 2 (the overall review)

### ISSUE THREAD

**Issue by haandahl** [kellylyke/whatshappening#9]
# Design/Code Review 3

#### Reviewer: Heidi Aandahl

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Project Overview**|| 
|Which planned functionality has been met? | | Rubric requirements are met: crud, hibernate, logging, new user. (I think you said it has multiple 1-many relationships)
|What planned functionality has not been met? | | Feed, following issues
|Describe the GitHub history and what it demonstrates about the project progress during the semester.| |Steady work with highest commit levels early in the semester as we learned new topics. 
|Describe how peer and instructor feedback/recommendations were incorporated into the project.| |I double checked closed issues, and they looked good. There is one open issue - looks like you could still add an assertion when you test your user removal to see what happens to the user's preferences.|
|Other comments/notes?| |(Reminder) You said the rest service does not belong in the project anymore.
|**JSPs**|| 
|Evaluate the JSPs for templating, business logic, data validation, overall look and feel.|  |Beautiful landing page! Fun gifs (of course)! Easy to look at in general.   Signing up: I was able to sign up with a 1-digit zip. When signing up, I got an error saying "we told you your passwords didn't match" when I had not been given any prior warning (testing on Firefox). However when I CHANGED my account it DID warn me about mismatched passwords.  Account change: I got a blank screen after changing my password on my account page. (http://18.218.215.98:8080/WhatsHappening/myAccountf).   I think you're aware of this but I clicked "view users" and got a non-friendly error screen.   Search is case-sensitive - you could add a note for users.  Watch List: could use a header 
|Other comments/notes?| |
|**Java code quality**| |
|Evaluate the code quality for the following and identify specific areas for improvement (class, method or line number)  single-purpose methods  well-structured project  descriptive naming of packages, classes, methods, variables  classes appropriately-sized  (no monster classes)   CPD (copy paste detection, meaning are the same lines of code repeated?)  are there candidates for super/subclass relationships, abstract classes, interfaces?  are any values hard-coded that should be in a properties file?  proper exception handling  proper error reporting to the user   code documentation |  | I'm using QAPlug to evaluate your code, which I know you have also run. I will screenshot what I see as higher priorities (or easy fixes) and put it in an issue. IntelliJ is showing me NO squiggly lines indicating repeated code - awesome job! I think your naming is clear. Methods and classes generally look well sized. Since the MemberDisplay servlet has a few methods separate from doGet it may be worth making a separate class. (May want to ask Paula for best practice there?)  In MyAccount the DoPost could be broken up a little. Javadoc is needed (as you know).
|Other comments/notes?| |
|**Logging**|Evaluate the use of logging, for example:  appropriate use of logging statements in the code for error logging and debugging   logging levels used - info, debug, error    no occurrences of  System.out.printlns or printStackTrace()    logging works on AWS deploy|Uses logging at different levels. Database.java has printStackTrace().
|Other comments/notes?| |
|**Unit Tests**|Evaluate the unit tests, for example:   tests are truly a unit test rather than a high level functional test   test data is appropriately cleaned up or handled    there is full coverage of methods that perform business logic or utility functions   redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After| You use @Before. Try testing methods in a more granular way - you can use protected methods instead of private. I know you are already working on coverage! :)
|Other comments/notes?| |
|**Security**||
|Evaluate authentication/authorization:|Is it implemented correctly and working locally as well as on AWS?|It works on AWS!
|Other comments/notes?| |DeleteUser.java should be protected in web.xml, right?
|**Web Service/API integration**||
|Evaluate the service/api integration, for example:    Which service/api is implemented?   How is  error handling of the service implemented? For example, what happens if the service is not available?| |Sorry forgot to write down the api - looks like propublica?.  You have some try/catch blocks associate with the api. In Search, there is a try/catch block that logs an error, which would've been thrown by methods in MemberSearch. I don't see where the user would be notified of an api error though. (You have some TODO's noted along those lines in MemberSearch.)
|Other comments/notes?| |
|**Independent research topic**| What is the independent research topic?| Project Lombok and sha256 
|Is the independent research topic/technique implemented in the project?| |Yes 
|Other comments/notes?| |
|**Deployment**| |
|Has the application been successfully deployed to AWS?| |Yes 
|Is the hosted application fully functioning?| |Yes, appears to be!
|Other comments/notes?| |

**Comment by kellylyke** [comment]
Thank you for your thorough review, Heidi! You hit on some things I have changed locally but not on AWS but that helps me know that they were in fact needed! I am going to update my testing and work something out for api errors.

**Comment by haandahl** [comment]
I figured you were on top of a lot of it, but you never know... : )
